### ISSUE TITLE
Why do I need a big frame height for the bars to be visible?

### ISSUE THREAD

**Issue by peterwarbo** [bastienFalcou/SoundWave#23]
If I have have a frame height of 70 the bars are nearly not visible. I need to have a frame height of around 300 for them to be clearly visible.

**Comment by bastienFalcou** [comment]
@peterwarbo the `height` of the bars is calculated according to the `height` of the view itself, so that the bars are never higher than the view.

If the view has a frame `height` of 70, the bars will never be higher than that. You need to increase the `height` of your view if you want to see the bars clearly.
